### hello world test
GET http://localhost:3000/

### Getting all list titles
GET http://localhost:3000/api/lists


### Getting a single list with its items
GET http://localhost:3000/api/lists/1

### Getting a another list with its items
GET http://localhost:3000/api/lists/3


### Create a new list title
POST http://localhost:3000/api/lists
Content-Type: application/json

{
    "listName": "Garden"
}

### Create another new list title
POST http://localhost:3000/api/lists
Content-Type: application/json

{
    "listName": "Sprouts"
}

###
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "list": 4,
    "itemName": "green beans"
}

###
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "list": 4,
    "itemName": "tomatoes"
}

###
DELETE http://localhost:3000/api/lists/4

###
DELETE http://localhost:3000/api/items/7
