### hello world test
GET http://localhost:3000/

### Getting all list titles
GET http://localhost:3000/api/lists


### Getting a single list with its items
GET http://localhost:3000/api/lists/1

### Getting a another list with its items
GET http://localhost:3000/api/lists/2


### Create a new list title
POST http://localhost:3000/api/lists
Content-Type: application/json

{
    "listName": "Garden"
}

### Create another new list
POST http://localhost:3000/api/lists
Content-Type: application/json

{
    "listName": "Sprouts"
}

### Adding a new item to a list
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "list": 6,
    "itemName": "green beans"
}

### Adding another new item
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "list": 4,
    "itemName": "tomatoes"
}

### Deleting a list
DELETE http://localhost:3000/api/lists/7


### Deleting a single item
DELETE http://localhost:3000/api/items/12
